import React, { useState } from 'react';
import type { ParserStage } from '../types/pipeline';

interface ASTViewerProps {
  parser: ParserStage;
}

export const ASTViewer: React.FC<ASTViewerProps> = ({ parser }) => {
  const [viewMode, setViewMode] = useState<'tree' | 'json'>('tree');

  if (parser.status === 'ERROR' && parser.error) {
    return (
      <div className="error-banner">
        <div className="error-banner-title">
          <span>✗ PARSER ERROR</span>
          {parser.error.line !== undefined && (
            <span>[Line {parser.error.line}, Col {parser.error.col}]</span>
          )}
        </div>
        <p style={{ marginTop: '4px' }}>{parser.error.message}</p>
      </div>
    );
  }

  if (parser.status === 'NOT_RUN' || !parser.ast_tree_text) {
    return <div style={{ color: 'var(--text-muted)' }}>Parser has not run yet. Execute a query to inspect the AST.</div>;
  }

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px', flexWrap: 'wrap', gap: '10px' }}>
        <div>
          <span style={{ color: 'var(--accent-mint)', fontWeight: 600, display: 'inline-flex', alignItems: 'center', gap: '6px' }}>
            <span>✓</span> Parsing successful
          </span>
          <span style={{ color: 'var(--text-secondary)', fontSize: '12px', marginLeft: '10px' }}>
            Generated by <code className="mono">backend.parser.Parser</code>
          </span>
        </div>
        <div style={{ display: 'flex', gap: '8px' }}>
          <button
            type="button"
            className="btn-secondary"
            onClick={() => setViewMode('tree')}
            style={viewMode === 'tree' ? { borderColor: 'var(--accent-violet-border)', color: 'var(--accent-violet-dark)', background: 'var(--accent-violet-bg)', fontWeight: 600 } : {}}
          >
            Diagram Tree View
          </button>
          <button
            type="button"
            className="btn-secondary"
            onClick={() => setViewMode('json')}
            style={viewMode === 'json' ? { borderColor: 'var(--accent-violet-border)', color: 'var(--accent-violet-dark)', background: 'var(--accent-violet-bg)', fontWeight: 600 } : {}}
          >
            Structured JSON
          </button>
        </div>
      </div>

      {viewMode === 'tree' ? (
        <div className="code-block" style={{ color: 'var(--accent-violet-dark)', fontWeight: 600, fontSize: '13.5px', lineHeight: '1.75' }}>
          {parser.ast_tree_text}
        </div>
      ) : (
        <pre className="code-block" style={{ color: '#0f172a', fontSize: '12.5px' }}>
          {JSON.stringify(parser.ast, null, 2)}
        </pre>
      )}
    </div>
  );
};
